name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Test contracts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '8.17.0'
      - name: Install build develop
        #run: sudo apt-get install build-essential
        run: sudo apt-get install make gcc g++ python git bash
      - name: Git setup
        run: git config --global url."https://".insteadOf git://
      - run: npm ci
      - run: npm test